# Generated by Django 4.2.1 on 2023-05-20 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_сategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='сategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.сategory'),
        ),
    ]
