# Generated by Django 4.2.1 on 2023-05-20 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_сategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='сategory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='сategory',
            field=models.ForeignKey(default='Без категорії', null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.сategory'),
        ),
    ]
