# Generated by Django 4.1.5 on 2023-05-21 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_сategory_image_url_alter_product_сategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='сategory',
            field=models.ForeignKey(default='Без категорії', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.сategory'),
        ),
    ]
