# Generated by Django 4.1.5 on 2023-05-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_сategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
