# Generated by Django 4.1.5 on 2023-05-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
